const data = [
    {
      category: "men",
      Image: "./image/menWear/asset 7.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 675,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 10.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 890,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 12.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 1000,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 13.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 340,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 14.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 680,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 15.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 908,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 16.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 675,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 17.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 675,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 18.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 905,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 19.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 756,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 24.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 1200,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 26.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 375,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 27.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 656,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 28.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 675,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 29.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 900,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 3.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 599,
    },
    {
      category: "men",
      Image: "./image/menWear/asset 4.jpeg",
      clothName: "U.S Polo Assn",
      CategoryName: "Long Sleeves Cotton T-shirt",
      PriceTag: 699,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 3.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 4.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 5.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 6.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 7.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 8.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 9.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 10.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 11.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 12.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 13.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 14.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 15.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 16.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 17.jpeg",
      clothName: "Sassafras",
      CategoryName: "High Neck Cropped Top",
      PriceTag: 399,
    },
    
    {
      category: "women",
      Image: "./image/womenWear/asset 23.jpeg",
      clothName: "Mast & Harbour",
      CategoryName: "Floral Print Cinched Waist Top",
      PriceTag: 400,
    },
    {
      category: "women",
      Image: "./image/womenWear/asset 24.jpeg",
      clothName: "Mast & Harbour",
      CategoryName: "Floral Print Cinched Waist Top",
      PriceTag: 500,
    },
    {
      category: "women",
      Image: "./image/womenWear/asset 25.jpeg",
      clothName: "Mast & Harbour",
      CategoryName: "Floral Print Cinched Waist Top",
      PriceTag: 340,
    },
    {
      category: "women",
      Image: "./image/womenWear/asset 25.jpeg",
      clothName: "Mast & Harbour",
      CategoryName: "Floral Print Cinched Waist Top",
      PriceTag: 450,
    },
    {
      category: "women",
      Image: "./image/womenWear/asset 26.jpeg",
      clothName: "Mast & Harbour",
      CategoryName: "Floral Print Cinched Waist Top",
      PriceTag: 456,
    },
    {
      category: "women",
      Image: "./image/womenWear/asset 27.jpeg",
      clothName: "Mast & Harbour",
      CategoryName: "Floral Print Cinched Waist Top",
      PriceTag: 902,
    },
    {
      category: "women",
      Image: "./image/womenWear/asset 28.jpeg",
      clothName: "Mast & Harbour",
      CategoryName: "Floral Print Cinched Waist Top",
      PriceTag: 289,
    },
    {
      category: "women",
      Image: "./image/womenWear/asset 29.jpeg",
      clothName: "Mast & Harbour",
      CategoryName: "Floral Print Cinched Waist Top",
      PriceTag: 902,
    },
    {
      category: "women",
      Image: "./image/womenWear/asset 30.jpeg",
      clothName: "Mast & Harbour",
      CategoryName: "Floral Print Cinched Waist Top",
      PriceTag: 560,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 3.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 4.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 5.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 6.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 7.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 8.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 9.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 10.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 12.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 13.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 14.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 15.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 16.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 17.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 18.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 19.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 20.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 21.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 22.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 23.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 24.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 25.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 26.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 27.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 28.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 29.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 30.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 31.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 32.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 33.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 34.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 35.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 36.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 37.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 38.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 39.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 40.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "kids",
      Image: "./image/kidsWear/asset 41.jpeg",
      clothName: "sangria",
      CategoryName: "kids Pure Cottan Cloths",
      PriceTag: 340,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 3.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 4.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 5.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 6.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 7.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 8.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 9.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 10.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 11.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 12.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 13.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: "2000",
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 14.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 15.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 16.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 17.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 18.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 19.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 20.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 21.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 22.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 23.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 24.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 25.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 26.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
    {
      category: "shoes",
      Image: "./image/shoes/asset 27.jpeg",
      clothName: "Puma",
      CategoryName: "Smashic brand Logo Shoes",
      PriceTag: 2000,
    },
  ];